language: ruby
rvm:
- 2.2.0
env:
  matrix:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
before_script:
- mysql -e 'create database my_app_test'
- psql -c 'create database my_app_test' -U postgres
bundler_args: "--binstubs=./bundler_stubs"
branches:
  only:
  - master
deploy:
  provider: heroku
  app: gentle-caverns-3821
  run: rake db:migrate
  api_key:
    secure: YwhAHE5P/vQl8TrxS0/osdHJ0EChKrqMmGIfUaWEIUPB8VVvRzVYSQbLG2I8fiG+MWJba4QSIacfeH7cY7mxf8KlErlPIkpj67gtcI8md8zHdHkpbKGWoiNGL8sW7ZNNGdkP23YvUartNfMGyDMt5X5W3tyV+lEPvOJAr3X8eTU=
