language: ruby
rvm:
  - 2.2.0
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
before_script:
  - mysql -e 'create database my_app_test'
  - psql -c 'create database my_app_test' -U postgres
bundler_args: --binstubs=./bundler_stubs

# whitelist
branches:
  only:
    - master

deploy:
  provider: heroku
  app: gentle-caverns-3821
  api-key: "99cdc82f-6766-4725-875c-3dabedbefc8c"
  run: "rake db:migrate"
