# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0048013f4e01cd75b52c0fc64b6cf06c3902dbb82f5f9adb5c967980e401658eea0735c3f1b41b62d9b58ee5ecbb538081495c792e32a1f15745af5ca9afdab2
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>

test:
  secret_key_base: 5f2cbb01a18accee5612cec61dec081a2b60f0ee5c40ed6e75fa1e03742d285bdf52a0a95c31d4a06582cf58a9e431babaa9ca7554cf2bbf6661be2588061600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
